### PR TITLE
added graphic showing pinouts of some of the jumpers

### PR DESCRIPTION
**Pull request by iplayfast**

### CODE REVIEW

**Comment by jadonk** [comment]
What is a .xcf file?

Let's try to get some of these doc items on the github wiki, rather than just the docs directory.

**Comment by iplayfast** [comment]
.xcf is a gimp file. I included it, since all the labels are separate 
layers. Easy to modify in an image.

Good idea about the wiki. Keep forgetting it's there.

**Comment by iplayfast** [comment]
I tried adding the image to the wiki but it's looking for an url. I don't have one, so I'll let you handle it.

**Comment by iplayfast** [comment]
OK, I added an image using the link from my fork of the repository. Feel free to update it if you want.

**Pull request merged**
